### ISSUE TITLE
support silent mode

### ISSUE THREAD

**Issue by huiwang** [r-zenine/sam#13]
the silent mode is very helpful when we need to pipe sam's output to other commands. 

for example, when I produce an output in json and then process it with jq, today, I've to do a reversed grep to filter out sam related output: `sam | grep -v SAM | jq`   

like curl, I'd expect something like `sam -s | jq`.

**Comment by r-zenine** [comment]
Thanks @huiwang for the input. I will implement that.

**Comment by r-zenine** [comment]
Implemented in v0.7.16
