### ISSUE TITLE
Provide dependencies information from command line

### ISSUE THREAD

**Issue by iyunbo** [r-zenine/sam#21]
Instead of relying on the `README.md` to provide information for installing required tools/commands and maintain it, we can provide actionable information: an instruction, a suitable link, or even an installation command, directly from the command line, so that as a user I would reduce the number of switches between my console and my browser.

One possible solution would be:

- introduce an optional directory, namely `dependencies`

- `dependencies` has only `vars.yaml`, which may provide some of the following for each `name`
  -  description of what to do
  -  installation command
  -  URL

- each time we got a 'command not found', sam should identify the name of the command (implicitly or explicitly), and search information from `dependencies`

**Comment by r-zenine** [comment]
Hello @iyunbo 
Thanks for the idea. 
Here is how I would see it work, tell me what you think : 
First, I'll introduce a `dependencies.yml` file where your can describe your dependencies and provide commands to install them on linux/macOS etc... 
Then I'll introduce a subcommand in `sam` called `install-dependencies`. 
This way, when you configure `sam` you can just call `sam install-dependencies` and you are good to go. 
wdyt ?

**Comment by iyunbo** [comment]
Yeah, it's better.
Some 'dependencies' may not be installable in an automatic way. 
Then the `install-dependencies` may behave a bit differently: eg. require actions outside of the command line.
