### ISSUE TITLE
introduce history feature and several "frequently" used shortcut commands

### ISSUE THREAD

**Issue by iyunbo** [r-zenine/sam#24]
keep a history of valid "final commands" (for example, based on optional $SAM_HISTORY_FILE env var).

and introduce some shortcut commands,
such as
- `sam !!` to re-run last command without re-setup all vars
- `sam !` to display last command without running it
- `sam %` to show latest and limited history of final commands 
- `sam xxx` to launch sam with pre-filter pattern 'xxx' (not related to history)

**Comment by r-zenine** [comment]
Super idea @iyunbo , 
I need some refactoring in the code before I can build that. But I will do it for sure :)
